# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/Shopify/logrus-bugsnag"

[[constraint]]
  name = "github.com/bugsnag/bugsnag-go"
  version = "1.1.1"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jpillora/backoff"
  version = "1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/superfly/tlstest"

[[constraint]]
  name = "github.com/tinylib/msgp"
  version = "1.0.2"

[[constraint]]
  name = "github.com/ulule/limiter"
  version = "1.0.0"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "0.5.2"

[[constraint]]
  name = "gopkg.in/ory-am/dockertest.v3"
  version = "3.0.9"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/rafaeljusto/redigomock"
  branch = "master"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"